### ISSUE TITLE
是不是已经失效了

### ISSUE THREAD

**Issue by Layty** [Redns/picgo-plugin-NutStore#1]
我的坚果有微信验证码的每次登录,是不是这样不行的

**Comment by Redns** [comment]
您好，每次登录都将刷新图片的外链，进而造成原链接失效。目前笔者正在尝试使用 `WebDAV` 上传访问坚果云，感谢您的支持

**Comment by A-little-bit-of-data** [comment]
> 您好，每次登录都将刷新图片的外链，进而造成原链接失效。目前笔者正在尝试使用 `WebDAV` 上传访问坚果云，感谢您的支持

您好，那要是关掉这个微信验证的话  是不是就可以用了？

**Comment by Redns** [comment]
目前仍然不清楚坚果云是否会不定时地自动刷新图片链接，您可以关闭微信验证后重试。另外，官方近期更新了相关接口，感觉可能会增加防盗链等机制，推荐您及时备份数据

**Comment by A-little-bit-of-data** [comment]
> 目前仍然不清楚坚果云是否会不定时地自动刷新图片链接，您可以关闭微信验证后重试。另外，官方近期更新了相关接口，感觉可能会增加防盗链等机制，推荐您及时备份数据

加了防盗链有啥别的办法能让自己本地访问到吗？

**Comment by Redns** [comment]
本地访问可以通过伪造 `Referer` 获取，但 `markdown` 通过链接肯定无法访问。
